name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e68773326eed9c3cbc054b53a4c90c5603012a8596ac64df6ee48e4f6a8cc8bb"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
