name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b583a0486180443ceea67c6fd25c22053328d11ef2f37cc06d567637d283ac07"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
