name = "HexxyCraft"
author = "HexxyCraft Team"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11cd9dafb0be9a841b71cf2a4547cdbf48fc0f41c01d1e52c0587eea673618b8"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "resources"
